### PR TITLE
Create models

### PR DESCRIPTION
**Pull request by chinhle23-zz**

### CODE REVIEW

**Comment by RedSkyAtMorning** [comment]
@faxedexcel Chinh, Would you please make a note in two places where you have ManyToManyFields, "#Anna thinks that this through is not supposed to be there, but certainly wants to try it with the through first'

**Comment by chinhle23-zz** [comment]
Okay Anna i'll make that change for Commented_by

**Comment by RedSkyAtMorning** [comment]
So, I'm good! @dmpeterson317 if you approve, then @faxedexcel and I give you the authority to merge. Let us know!

**Comment by dpeterzen** [comment]
I think you should remove voted_by, we already handle the one to many relationship in the vote model.

**Pull request merged**
