### PR TITLE
Dan sorting view

### PR DESCRIPTION
**Pull request by dpeterzen**

### CODE REVIEW

**Review by chinhle23-zz — COMMENTED** [review]
I get an error when I try to go to http://127.0.0.1:8000/: 

I get Page not Found error

Request Method: | GET
-- | --
http://127.0.0.1:8000/core/



Request Method: | GET
-- | --
http://127.0.0.1:8000/core/


Request Method: | GET
-- | --
http://127.0.0.1:8000/core/


Request Method: | GET
-- | --
http://127.0.0.1:8000/core/

**Review by chinhle23-zz — APPROVED** [review]
this piece looks good and works for me

**Comment by chinhle23-zz** [comment]
Sorry, I thought I could comment on each commit, but it doesn't look like it's doing that...

I'm good with Submitter fix. It works.

the urls changes you made doesn't work for me

**Comment by RedSkyAtMorning** [comment]
looks good to me

**Pull request merged**
